"""initial schema

Revision ID: 2ce3a602a251
Revises: 
Create Date: 2026-06-23 21:41:09.537433
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2ce3a602a251'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('avg_pace', sa.String(length=16), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hr_zones', sa.JSON(), nullable=True),
    sa.Column('splits_km', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garmin_activity_id', name='uq_activity_garmin_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_garmin_activity_id'), ['garmin_activity_id'], unique=False)

    op.create_table('coaching_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('next_workout', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coaching_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coaching_reports_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_reports_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaching_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_coaching_reports_activity_id'))

    op.drop_table('coaching_reports')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_garmin_activity_id'))
        batch_op.drop_index(batch_op.f('ix_activities_date'))

    op.drop_table('activities')
    # ### end Alembic commands ###
