"""athlete level and risk tolerance

Revision ID: 8c7fc8a12013
Revises: bf76056f2179
Create Date: 2026-06-25 14:35:08.018017
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8c7fc8a12013'
down_revision: str | None = 'bf76056f2179'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('risk_tolerance', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.drop_column('risk_tolerance')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
