"""athlete profile and goal

Revision ID: 8ea1979f712e
Revises: 2ce3a602a251
Create Date: 2026-06-24 10:51:23.474085
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8ea1979f712e'
down_revision: str | None = '2ce3a602a251'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('weekly_runs', sa.Integer(), nullable=True),
    sa.Column('available_days', sa.JSON(), nullable=True),
    sa.Column('zones', sa.JSON(), nullable=True),
    sa.Column('physiology', sa.JSON(), nullable=True),
    sa.Column('goal_type', sa.String(length=32), nullable=True),
    sa.Column('goal_target_date', sa.String(length=10), nullable=True),
    sa.Column('goal_target_time', sa.String(length=16), nullable=True),
    sa.Column('goal_priority', sa.String(length=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_profile')
    # ### end Alembic commands ###
