"""checkins, races, weather and trail fields

Revision ID: f9e70191b8b5
Revises: 8ea1979f712e
Create Date: 2026-06-24 11:16:56.506385
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f9e70191b8b5'
down_revision: str | None = '8ea1979f712e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('sleep_h', sa.Float(), nullable=True),
    sa.Column('fatigue', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_checkin_date')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkins_date'), ['date'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humidity_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('elevation_loss_m', sa.Float(), nullable=True))

    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('races', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.drop_column('races')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('elevation_loss_m')
        batch_op.drop_column('humidity_pct')
        batch_op.drop_column('temperature_c')

    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkins_date'))

    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
