"""garmin rich metrics on activities

Revision ID: bf76056f2179
Revises: f9e70191b8b5
Create Date: 2026-06-25 09:18:58.465638
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bf76056f2179'
down_revision: str | None = 'f9e70191b8b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_training_load', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vigorous_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('moderate_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('body_battery_delta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stamina_drop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_grade_adjusted_pace', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('fastest_split_1k', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('fastest_split_5k', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('vo2max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aerobic_te_message', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('anaerobic_te_message', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('anaerobic_te_message')
        batch_op.drop_column('aerobic_te_message')
        batch_op.drop_column('vo2max')
        batch_op.drop_column('fastest_split_5k')
        batch_op.drop_column('fastest_split_1k')
        batch_op.drop_column('avg_grade_adjusted_pace')
        batch_op.drop_column('stamina_drop')
        batch_op.drop_column('body_battery_delta')
        batch_op.drop_column('moderate_minutes')
        batch_op.drop_column('vigorous_minutes')
        batch_op.drop_column('garmin_training_load')

    # ### end Alembic commands ###
